### ISSUE TITLE
Add healthchecks support

### ISSUE THREAD

**Issue by insani7y** [community-of-python/microbootstrap#5]
Add health checks to litestar and fastapi after healthchecks package is moved to opensource

**Comment by vrslev** [comment]
@insani7y  Currently we have this defined in ~100% services:

```python
import typing

from health_checks.http_based import DefaultHTTPHealthCheck
from health_checks.litestar_healthcheck import build_litestar_health_check_router

from service.settings import settings


HEALTH_CHECKS_ROUTER: typing.Final = build_litestar_health_check_router(
    health_check=DefaultHTTPHealthCheck(
        service_version=settings.service_version,
        service_name=settings.service_name,
    )
)
```

Do you think we should continue using `DefaultHTTPHealthCheck`, or some sotisficated configuration is needed?

**Comment by insani7y** [comment]
Yeah, i think, it would be good to have a `health_check_enabled` param to toggle this functionality.
`service_version` and `service_name` will be passed down, so, all the same, but less boilerplate
