### ISSUE TITLE
Add support for more interfaces and loops in granian

### ISSUE THREAD

**Issue by Mernus** [community-of-python/microbootstrap#6]
I think it will be good if we can make configuring granian server more optionally and do not set any parameters directly.
So for future i think we need to investigate this question and add some support for this parameters if we can.

**Comment by insani7y** [comment]
it looks like this issue is duplicates #3 you can add some description there
and take it if you want to

**Comment by Mernus** [comment]
Yea that issue may contains also this issue. Will add info about this to it.
